/**
 * QUIZ Module API Client
 * Auto-generated by FastVue Module System
 */

import { requestClient } from '#/api/request';


// =============================================================================
// LIST API
// =============================================================================

export namespace ListApi {
  export interface List {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface ListCreate {
    name: string;
    [key: string]: any;
  }

  export interface ListUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: List[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getListsApi(params?: ListApi.ListParams) {
  return requestClient.get<ListApi.ListResponse>('/quiz/list/', { params });
}

export async function getListApi(id: number) {
  return requestClient.get<ListApi.List>(`/quiz/list/${id}`);
}

export async function createListApi(data: ListApi.ListCreate) {
  return requestClient.post<ListApi.List>('/quiz/list/', data);
}

export async function updateListApi(id: number, data: ListApi.ListUpdate) {
  return requestClient.put<ListApi.List>(`/quiz/list/${id}`, data);
}

export async function deleteListApi(id: number) {
  return requestClient.delete(`/quiz/list/${id}`);
}

// =============================================================================
// MY ATTEMPTS API
// =============================================================================

export namespace MyAttemptsApi {
  export interface MyAttempts {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface MyAttemptsCreate {
    name: string;
    [key: string]: any;
  }

  export interface MyAttemptsUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: MyAttempts[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getMyAttemptssApi(params?: MyAttemptsApi.ListParams) {
  return requestClient.get<MyAttemptsApi.ListResponse>('/quiz/my-attempts/', { params });
}

export async function getMyAttemptsApi(id: number) {
  return requestClient.get<MyAttemptsApi.MyAttempts>(`/quiz/my-attempts/${id}`);
}

export async function createMyAttemptsApi(data: MyAttemptsApi.MyAttemptsCreate) {
  return requestClient.post<MyAttemptsApi.MyAttempts>('/quiz/my-attempts/', data);
}

export async function updateMyAttemptsApi(id: number, data: MyAttemptsApi.MyAttemptsUpdate) {
  return requestClient.put<MyAttemptsApi.MyAttempts>(`/quiz/my-attempts/${id}`, data);
}

export async function deleteMyAttemptsApi(id: number) {
  return requestClient.delete(`/quiz/my-attempts/${id}`);
}

// =============================================================================
// QUESTIONS API
// =============================================================================

export namespace QuestionsApi {
  export interface Questions {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface QuestionsCreate {
    name: string;
    [key: string]: any;
  }

  export interface QuestionsUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Questions[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getQuestionssApi(params?: QuestionsApi.ListParams) {
  return requestClient.get<QuestionsApi.ListResponse>('/quiz/questions/', { params });
}

export async function getQuestionsApi(id: number) {
  return requestClient.get<QuestionsApi.Questions>(`/quiz/questions/${id}`);
}

export async function createQuestionsApi(data: QuestionsApi.QuestionsCreate) {
  return requestClient.post<QuestionsApi.Questions>('/quiz/questions/', data);
}

export async function updateQuestionsApi(id: number, data: QuestionsApi.QuestionsUpdate) {
  return requestClient.put<QuestionsApi.Questions>(`/quiz/questions/${id}`, data);
}

export async function deleteQuestionsApi(id: number) {
  return requestClient.delete(`/quiz/questions/${id}`);
}

// =============================================================================
// ANALYTICS API
// =============================================================================

export namespace AnalyticsApi {
  export interface Analytics {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface AnalyticsCreate {
    name: string;
    [key: string]: any;
  }

  export interface AnalyticsUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Analytics[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getAnalyticssApi(params?: AnalyticsApi.ListParams) {
  return requestClient.get<AnalyticsApi.ListResponse>('/quiz/analytics/', { params });
}

export async function getAnalyticsApi(id: number) {
  return requestClient.get<AnalyticsApi.Analytics>(`/quiz/analytics/${id}`);
}

export async function createAnalyticsApi(data: AnalyticsApi.AnalyticsCreate) {
  return requestClient.post<AnalyticsApi.Analytics>('/quiz/analytics/', data);
}

export async function updateAnalyticsApi(id: number, data: AnalyticsApi.AnalyticsUpdate) {
  return requestClient.put<AnalyticsApi.Analytics>(`/quiz/analytics/${id}`, data);
}

export async function deleteAnalyticsApi(id: number) {
  return requestClient.delete(`/quiz/analytics/${id}`);
}

