/**
 * RECRUITMENT Module API Client
 * Auto-generated by FastVue Module System
 */

import { requestClient } from '#/api/request';


// =============================================================================
// REPORTS API
// =============================================================================

export namespace ReportsApi {
  export interface Reports {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface ReportsCreate {
    name: string;
    [key: string]: any;
  }

  export interface ReportsUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Reports[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getReportssApi(params?: ReportsApi.ListParams) {
  return requestClient.get<ReportsApi.ListResponse>('/recruitment/reports/', { params });
}

export async function getReportsApi(id: number) {
  return requestClient.get<ReportsApi.Reports>(`/recruitment/reports/${id}`);
}

export async function createReportsApi(data: ReportsApi.ReportsCreate) {
  return requestClient.post<ReportsApi.Reports>('/recruitment/reports/', data);
}

export async function updateReportsApi(id: number, data: ReportsApi.ReportsUpdate) {
  return requestClient.put<ReportsApi.Reports>(`/recruitment/reports/${id}`, data);
}

export async function deleteReportsApi(id: number) {
  return requestClient.delete(`/recruitment/reports/${id}`);
}

// =============================================================================
// PIPELINE API
// =============================================================================

export namespace PipelineApi {
  export interface Pipeline {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface PipelineCreate {
    name: string;
    [key: string]: any;
  }

  export interface PipelineUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Pipeline[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getPipelinesApi(params?: PipelineApi.ListParams) {
  return requestClient.get<PipelineApi.ListResponse>('/recruitment/pipeline/', { params });
}

export async function getPipelineApi(id: number) {
  return requestClient.get<PipelineApi.Pipeline>(`/recruitment/pipeline/${id}`);
}

export async function createPipelineApi(data: PipelineApi.PipelineCreate) {
  return requestClient.post<PipelineApi.Pipeline>('/recruitment/pipeline/', data);
}

export async function updatePipelineApi(id: number, data: PipelineApi.PipelineUpdate) {
  return requestClient.put<PipelineApi.Pipeline>(`/recruitment/pipeline/${id}`, data);
}

export async function deletePipelineApi(id: number) {
  return requestClient.delete(`/recruitment/pipeline/${id}`);
}

// =============================================================================
// JOBS API
// =============================================================================

export namespace JobsApi {
  export interface Jobs {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface JobsCreate {
    name: string;
    [key: string]: any;
  }

  export interface JobsUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Jobs[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getJobssApi(params?: JobsApi.ListParams) {
  return requestClient.get<JobsApi.ListResponse>('/recruitment/jobs/', { params });
}

export async function getJobsApi(id: number) {
  return requestClient.get<JobsApi.Jobs>(`/recruitment/jobs/${id}`);
}

export async function createJobsApi(data: JobsApi.JobsCreate) {
  return requestClient.post<JobsApi.Jobs>('/recruitment/jobs/', data);
}

export async function updateJobsApi(id: number, data: JobsApi.JobsUpdate) {
  return requestClient.put<JobsApi.Jobs>(`/recruitment/jobs/${id}`, data);
}

export async function deleteJobsApi(id: number) {
  return requestClient.delete(`/recruitment/jobs/${id}`);
}

// =============================================================================
// CANDIDATES API
// =============================================================================

export namespace CandidatesApi {
  export interface Candidates {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface CandidatesCreate {
    name: string;
    [key: string]: any;
  }

  export interface CandidatesUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Candidates[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getCandidatessApi(params?: CandidatesApi.ListParams) {
  return requestClient.get<CandidatesApi.ListResponse>('/recruitment/candidates/', { params });
}

export async function getCandidatesApi(id: number) {
  return requestClient.get<CandidatesApi.Candidates>(`/recruitment/candidates/${id}`);
}

export async function createCandidatesApi(data: CandidatesApi.CandidatesCreate) {
  return requestClient.post<CandidatesApi.Candidates>('/recruitment/candidates/', data);
}

export async function updateCandidatesApi(id: number, data: CandidatesApi.CandidatesUpdate) {
  return requestClient.put<CandidatesApi.Candidates>(`/recruitment/candidates/${id}`, data);
}

export async function deleteCandidatesApi(id: number) {
  return requestClient.delete(`/recruitment/candidates/${id}`);
}

// =============================================================================
// INTERVIEWS API
// =============================================================================

export namespace InterviewsApi {
  export interface Interviews {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface InterviewsCreate {
    name: string;
    [key: string]: any;
  }

  export interface InterviewsUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Interviews[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getInterviewssApi(params?: InterviewsApi.ListParams) {
  return requestClient.get<InterviewsApi.ListResponse>('/recruitment/interviews/', { params });
}

export async function getInterviewsApi(id: number) {
  return requestClient.get<InterviewsApi.Interviews>(`/recruitment/interviews/${id}`);
}

export async function createInterviewsApi(data: InterviewsApi.InterviewsCreate) {
  return requestClient.post<InterviewsApi.Interviews>('/recruitment/interviews/', data);
}

export async function updateInterviewsApi(id: number, data: InterviewsApi.InterviewsUpdate) {
  return requestClient.put<InterviewsApi.Interviews>(`/recruitment/interviews/${id}`, data);
}

export async function deleteInterviewsApi(id: number) {
  return requestClient.delete(`/recruitment/interviews/${id}`);
}

// =============================================================================
// INTERVIEW FEEDBACK API
// =============================================================================

export namespace InterviewFeedbackApi {
  export interface InterviewFeedback {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface InterviewFeedbackCreate {
    name: string;
    [key: string]: any;
  }

  export interface InterviewFeedbackUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: InterviewFeedback[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getInterviewFeedbacksApi(params?: InterviewFeedbackApi.ListParams) {
  return requestClient.get<InterviewFeedbackApi.ListResponse>('/recruitment/interview-feedback/', { params });
}

export async function getInterviewFeedbackApi(id: number) {
  return requestClient.get<InterviewFeedbackApi.InterviewFeedback>(`/recruitment/interview-feedback/${id}`);
}

export async function createInterviewFeedbackApi(data: InterviewFeedbackApi.InterviewFeedbackCreate) {
  return requestClient.post<InterviewFeedbackApi.InterviewFeedback>('/recruitment/interview-feedback/', data);
}

export async function updateInterviewFeedbackApi(id: number, data: InterviewFeedbackApi.InterviewFeedbackUpdate) {
  return requestClient.put<InterviewFeedbackApi.InterviewFeedback>(`/recruitment/interview-feedback/${id}`, data);
}

export async function deleteInterviewFeedbackApi(id: number) {
  return requestClient.delete(`/recruitment/interview-feedback/${id}`);
}

// =============================================================================
// INTERVIEW QUESTIONS API
// =============================================================================

export namespace InterviewQuestionsApi {
  export interface InterviewQuestions {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface InterviewQuestionsCreate {
    name: string;
    [key: string]: any;
  }

  export interface InterviewQuestionsUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: InterviewQuestions[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getInterviewQuestionssApi(params?: InterviewQuestionsApi.ListParams) {
  return requestClient.get<InterviewQuestionsApi.ListResponse>('/recruitment/interview-questions/', { params });
}

export async function getInterviewQuestionsApi(id: number) {
  return requestClient.get<InterviewQuestionsApi.InterviewQuestions>(`/recruitment/interview-questions/${id}`);
}

export async function createInterviewQuestionsApi(data: InterviewQuestionsApi.InterviewQuestionsCreate) {
  return requestClient.post<InterviewQuestionsApi.InterviewQuestions>('/recruitment/interview-questions/', data);
}

export async function updateInterviewQuestionsApi(id: number, data: InterviewQuestionsApi.InterviewQuestionsUpdate) {
  return requestClient.put<InterviewQuestionsApi.InterviewQuestions>(`/recruitment/interview-questions/${id}`, data);
}

export async function deleteInterviewQuestionsApi(id: number) {
  return requestClient.delete(`/recruitment/interview-questions/${id}`);
}

// =============================================================================
// INTERVIEW SCORECARDS API
// =============================================================================

export namespace InterviewScorecardsApi {
  export interface InterviewScorecards {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface InterviewScorecardsCreate {
    name: string;
    [key: string]: any;
  }

  export interface InterviewScorecardsUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: InterviewScorecards[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getInterviewScorecardssApi(params?: InterviewScorecardsApi.ListParams) {
  return requestClient.get<InterviewScorecardsApi.ListResponse>('/recruitment/interview-scorecards/', { params });
}

export async function getInterviewScorecardsApi(id: number) {
  return requestClient.get<InterviewScorecardsApi.InterviewScorecards>(`/recruitment/interview-scorecards/${id}`);
}

export async function createInterviewScorecardsApi(data: InterviewScorecardsApi.InterviewScorecardsCreate) {
  return requestClient.post<InterviewScorecardsApi.InterviewScorecards>('/recruitment/interview-scorecards/', data);
}

export async function updateInterviewScorecardsApi(id: number, data: InterviewScorecardsApi.InterviewScorecardsUpdate) {
  return requestClient.put<InterviewScorecardsApi.InterviewScorecards>(`/recruitment/interview-scorecards/${id}`, data);
}

export async function deleteInterviewScorecardsApi(id: number) {
  return requestClient.delete(`/recruitment/interview-scorecards/${id}`);
}

// =============================================================================
// INTERVIEW AVAILABILITY API
// =============================================================================

export namespace InterviewAvailabilityApi {
  export interface InterviewAvailability {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface InterviewAvailabilityCreate {
    name: string;
    [key: string]: any;
  }

  export interface InterviewAvailabilityUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: InterviewAvailability[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getInterviewAvailabilitysApi(params?: InterviewAvailabilityApi.ListParams) {
  return requestClient.get<InterviewAvailabilityApi.ListResponse>('/recruitment/interview-availability/', { params });
}

export async function getInterviewAvailabilityApi(id: number) {
  return requestClient.get<InterviewAvailabilityApi.InterviewAvailability>(`/recruitment/interview-availability/${id}`);
}

export async function createInterviewAvailabilityApi(data: InterviewAvailabilityApi.InterviewAvailabilityCreate) {
  return requestClient.post<InterviewAvailabilityApi.InterviewAvailability>('/recruitment/interview-availability/', data);
}

export async function updateInterviewAvailabilityApi(id: number, data: InterviewAvailabilityApi.InterviewAvailabilityUpdate) {
  return requestClient.put<InterviewAvailabilityApi.InterviewAvailability>(`/recruitment/interview-availability/${id}`, data);
}

export async function deleteInterviewAvailabilityApi(id: number) {
  return requestClient.delete(`/recruitment/interview-availability/${id}`);
}

// =============================================================================
// TALENT POOLS API
// =============================================================================

export namespace TalentPoolsApi {
  export interface TalentPools {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface TalentPoolsCreate {
    name: string;
    [key: string]: any;
  }

  export interface TalentPoolsUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: TalentPools[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getTalentPoolssApi(params?: TalentPoolsApi.ListParams) {
  return requestClient.get<TalentPoolsApi.ListResponse>('/recruitment/talent-pools/', { params });
}

export async function getTalentPoolsApi(id: number) {
  return requestClient.get<TalentPoolsApi.TalentPools>(`/recruitment/talent-pools/${id}`);
}

export async function createTalentPoolsApi(data: TalentPoolsApi.TalentPoolsCreate) {
  return requestClient.post<TalentPoolsApi.TalentPools>('/recruitment/talent-pools/', data);
}

export async function updateTalentPoolsApi(id: number, data: TalentPoolsApi.TalentPoolsUpdate) {
  return requestClient.put<TalentPoolsApi.TalentPools>(`/recruitment/talent-pools/${id}`, data);
}

export async function deleteTalentPoolsApi(id: number) {
  return requestClient.delete(`/recruitment/talent-pools/${id}`);
}

// =============================================================================
// QUESTIONNAIRES API
// =============================================================================

export namespace QuestionnairesApi {
  export interface Questionnaires {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface QuestionnairesCreate {
    name: string;
    [key: string]: any;
  }

  export interface QuestionnairesUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Questionnaires[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getQuestionnairessApi(params?: QuestionnairesApi.ListParams) {
  return requestClient.get<QuestionnairesApi.ListResponse>('/recruitment/questionnaires/', { params });
}

export async function getQuestionnairesApi(id: number) {
  return requestClient.get<QuestionnairesApi.Questionnaires>(`/recruitment/questionnaires/${id}`);
}

export async function createQuestionnairesApi(data: QuestionnairesApi.QuestionnairesCreate) {
  return requestClient.post<QuestionnairesApi.Questionnaires>('/recruitment/questionnaires/', data);
}

export async function updateQuestionnairesApi(id: number, data: QuestionnairesApi.QuestionnairesUpdate) {
  return requestClient.put<QuestionnairesApi.Questionnaires>(`/recruitment/questionnaires/${id}`, data);
}

export async function deleteQuestionnairesApi(id: number) {
  return requestClient.delete(`/recruitment/questionnaires/${id}`);
}

// =============================================================================
// SCORING API
// =============================================================================

export namespace ScoringApi {
  export interface Scoring {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface ScoringCreate {
    name: string;
    [key: string]: any;
  }

  export interface ScoringUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Scoring[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getScoringsApi(params?: ScoringApi.ListParams) {
  return requestClient.get<ScoringApi.ListResponse>('/recruitment/scoring/', { params });
}

export async function getScoringApi(id: number) {
  return requestClient.get<ScoringApi.Scoring>(`/recruitment/scoring/${id}`);
}

export async function createScoringApi(data: ScoringApi.ScoringCreate) {
  return requestClient.post<ScoringApi.Scoring>('/recruitment/scoring/', data);
}

export async function updateScoringApi(id: number, data: ScoringApi.ScoringUpdate) {
  return requestClient.put<ScoringApi.Scoring>(`/recruitment/scoring/${id}`, data);
}

export async function deleteScoringApi(id: number) {
  return requestClient.delete(`/recruitment/scoring/${id}`);
}

// =============================================================================
// OFFERS API
// =============================================================================

export namespace OffersApi {
  export interface Offers {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface OffersCreate {
    name: string;
    [key: string]: any;
  }

  export interface OffersUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Offers[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getOfferssApi(params?: OffersApi.ListParams) {
  return requestClient.get<OffersApi.ListResponse>('/recruitment/offers/', { params });
}

export async function getOffersApi(id: number) {
  return requestClient.get<OffersApi.Offers>(`/recruitment/offers/${id}`);
}

export async function createOffersApi(data: OffersApi.OffersCreate) {
  return requestClient.post<OffersApi.Offers>('/recruitment/offers/', data);
}

export async function updateOffersApi(id: number, data: OffersApi.OffersUpdate) {
  return requestClient.put<OffersApi.Offers>(`/recruitment/offers/${id}`, data);
}

export async function deleteOffersApi(id: number) {
  return requestClient.delete(`/recruitment/offers/${id}`);
}

// =============================================================================
// SOURCING API
// =============================================================================

export namespace SourcingApi {
  export interface Sourcing {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface SourcingCreate {
    name: string;
    [key: string]: any;
  }

  export interface SourcingUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Sourcing[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getSourcingsApi(params?: SourcingApi.ListParams) {
  return requestClient.get<SourcingApi.ListResponse>('/recruitment/sourcing/', { params });
}

export async function getSourcingApi(id: number) {
  return requestClient.get<SourcingApi.Sourcing>(`/recruitment/sourcing/${id}`);
}

export async function createSourcingApi(data: SourcingApi.SourcingCreate) {
  return requestClient.post<SourcingApi.Sourcing>('/recruitment/sourcing/', data);
}

export async function updateSourcingApi(id: number, data: SourcingApi.SourcingUpdate) {
  return requestClient.put<SourcingApi.Sourcing>(`/recruitment/sourcing/${id}`, data);
}

export async function deleteSourcingApi(id: number) {
  return requestClient.delete(`/recruitment/sourcing/${id}`);
}

// =============================================================================
// INTERVIEW KITS API
// =============================================================================

export namespace InterviewKitsApi {
  export interface InterviewKits {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface InterviewKitsCreate {
    name: string;
    [key: string]: any;
  }

  export interface InterviewKitsUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: InterviewKits[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getInterviewKitssApi(params?: InterviewKitsApi.ListParams) {
  return requestClient.get<InterviewKitsApi.ListResponse>('/recruitment/interview-kits/', { params });
}

export async function getInterviewKitsApi(id: number) {
  return requestClient.get<InterviewKitsApi.InterviewKits>(`/recruitment/interview-kits/${id}`);
}

export async function createInterviewKitsApi(data: InterviewKitsApi.InterviewKitsCreate) {
  return requestClient.post<InterviewKitsApi.InterviewKits>('/recruitment/interview-kits/', data);
}

export async function updateInterviewKitsApi(id: number, data: InterviewKitsApi.InterviewKitsUpdate) {
  return requestClient.put<InterviewKitsApi.InterviewKits>(`/recruitment/interview-kits/${id}`, data);
}

export async function deleteInterviewKitsApi(id: number) {
  return requestClient.delete(`/recruitment/interview-kits/${id}`);
}

// =============================================================================
// DEI API
// =============================================================================

export namespace DeiApi {
  export interface Dei {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface DeiCreate {
    name: string;
    [key: string]: any;
  }

  export interface DeiUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Dei[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getDeisApi(params?: DeiApi.ListParams) {
  return requestClient.get<DeiApi.ListResponse>('/recruitment/dei/', { params });
}

export async function getDeiApi(id: number) {
  return requestClient.get<DeiApi.Dei>(`/recruitment/dei/${id}`);
}

export async function createDeiApi(data: DeiApi.DeiCreate) {
  return requestClient.post<DeiApi.Dei>('/recruitment/dei/', data);
}

export async function updateDeiApi(id: number, data: DeiApi.DeiUpdate) {
  return requestClient.put<DeiApi.Dei>(`/recruitment/dei/${id}`, data);
}

export async function deleteDeiApi(id: number) {
  return requestClient.delete(`/recruitment/dei/${id}`);
}

// =============================================================================
// AUTOMATION API
// =============================================================================

export namespace AutomationApi {
  export interface Automation {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface AutomationCreate {
    name: string;
    [key: string]: any;
  }

  export interface AutomationUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Automation[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getAutomationsApi(params?: AutomationApi.ListParams) {
  return requestClient.get<AutomationApi.ListResponse>('/recruitment/automation/', { params });
}

export async function getAutomationApi(id: number) {
  return requestClient.get<AutomationApi.Automation>(`/recruitment/automation/${id}`);
}

export async function createAutomationApi(data: AutomationApi.AutomationCreate) {
  return requestClient.post<AutomationApi.Automation>('/recruitment/automation/', data);
}

export async function updateAutomationApi(id: number, data: AutomationApi.AutomationUpdate) {
  return requestClient.put<AutomationApi.Automation>(`/recruitment/automation/${id}`, data);
}

export async function deleteAutomationApi(id: number) {
  return requestClient.delete(`/recruitment/automation/${id}`);
}

// =============================================================================
// EVALUATION TEMPLATES API
// =============================================================================

export namespace EvaluationTemplatesApi {
  export interface EvaluationTemplates {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface EvaluationTemplatesCreate {
    name: string;
    [key: string]: any;
  }

  export interface EvaluationTemplatesUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: EvaluationTemplates[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getEvaluationTemplatessApi(params?: EvaluationTemplatesApi.ListParams) {
  return requestClient.get<EvaluationTemplatesApi.ListResponse>('/recruitment/evaluation-templates/', { params });
}

export async function getEvaluationTemplatesApi(id: number) {
  return requestClient.get<EvaluationTemplatesApi.EvaluationTemplates>(`/recruitment/evaluation-templates/${id}`);
}

export async function createEvaluationTemplatesApi(data: EvaluationTemplatesApi.EvaluationTemplatesCreate) {
  return requestClient.post<EvaluationTemplatesApi.EvaluationTemplates>('/recruitment/evaluation-templates/', data);
}

export async function updateEvaluationTemplatesApi(id: number, data: EvaluationTemplatesApi.EvaluationTemplatesUpdate) {
  return requestClient.put<EvaluationTemplatesApi.EvaluationTemplates>(`/recruitment/evaluation-templates/${id}`, data);
}

export async function deleteEvaluationTemplatesApi(id: number) {
  return requestClient.delete(`/recruitment/evaluation-templates/${id}`);
}

// =============================================================================
// EVALUATION TEMPLATE FORM API
// =============================================================================

export namespace EvaluationTemplateFormApi {
  export interface EvaluationTemplateForm {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface EvaluationTemplateFormCreate {
    name: string;
    [key: string]: any;
  }

  export interface EvaluationTemplateFormUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: EvaluationTemplateForm[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getEvaluationTemplateFormsApi(params?: EvaluationTemplateFormApi.ListParams) {
  return requestClient.get<EvaluationTemplateFormApi.ListResponse>('/recruitment/evaluation-template-form/', { params });
}

export async function getEvaluationTemplateFormApi(id: number) {
  return requestClient.get<EvaluationTemplateFormApi.EvaluationTemplateForm>(`/recruitment/evaluation-template-form/${id}`);
}

export async function createEvaluationTemplateFormApi(data: EvaluationTemplateFormApi.EvaluationTemplateFormCreate) {
  return requestClient.post<EvaluationTemplateFormApi.EvaluationTemplateForm>('/recruitment/evaluation-template-form/', data);
}

export async function updateEvaluationTemplateFormApi(id: number, data: EvaluationTemplateFormApi.EvaluationTemplateFormUpdate) {
  return requestClient.put<EvaluationTemplateFormApi.EvaluationTemplateForm>(`/recruitment/evaluation-template-form/${id}`, data);
}

export async function deleteEvaluationTemplateFormApi(id: number) {
  return requestClient.delete(`/recruitment/evaluation-template-form/${id}`);
}

// =============================================================================
// EVALUATION CONDUCT API
// =============================================================================

export namespace EvaluationConductApi {
  export interface EvaluationConduct {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface EvaluationConductCreate {
    name: string;
    [key: string]: any;
  }

  export interface EvaluationConductUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: EvaluationConduct[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getEvaluationConductsApi(params?: EvaluationConductApi.ListParams) {
  return requestClient.get<EvaluationConductApi.ListResponse>('/recruitment/evaluation-conduct/', { params });
}

export async function getEvaluationConductApi(id: number) {
  return requestClient.get<EvaluationConductApi.EvaluationConduct>(`/recruitment/evaluation-conduct/${id}`);
}

export async function createEvaluationConductApi(data: EvaluationConductApi.EvaluationConductCreate) {
  return requestClient.post<EvaluationConductApi.EvaluationConduct>('/recruitment/evaluation-conduct/', data);
}

export async function updateEvaluationConductApi(id: number, data: EvaluationConductApi.EvaluationConductUpdate) {
  return requestClient.put<EvaluationConductApi.EvaluationConduct>(`/recruitment/evaluation-conduct/${id}`, data);
}

export async function deleteEvaluationConductApi(id: number) {
  return requestClient.delete(`/recruitment/evaluation-conduct/${id}`);
}

// =============================================================================
// EVALUATION SCORECARD API
// =============================================================================

export namespace EvaluationScorecardApi {
  export interface EvaluationScorecard {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface EvaluationScorecardCreate {
    name: string;
    [key: string]: any;
  }

  export interface EvaluationScorecardUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: EvaluationScorecard[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getEvaluationScorecardsApi(params?: EvaluationScorecardApi.ListParams) {
  return requestClient.get<EvaluationScorecardApi.ListResponse>('/recruitment/evaluation-scorecard/', { params });
}

export async function getEvaluationScorecardApi(id: number) {
  return requestClient.get<EvaluationScorecardApi.EvaluationScorecard>(`/recruitment/evaluation-scorecard/${id}`);
}

export async function createEvaluationScorecardApi(data: EvaluationScorecardApi.EvaluationScorecardCreate) {
  return requestClient.post<EvaluationScorecardApi.EvaluationScorecard>('/recruitment/evaluation-scorecard/', data);
}

export async function updateEvaluationScorecardApi(id: number, data: EvaluationScorecardApi.EvaluationScorecardUpdate) {
  return requestClient.put<EvaluationScorecardApi.EvaluationScorecard>(`/recruitment/evaluation-scorecard/${id}`, data);
}

export async function deleteEvaluationScorecardApi(id: number) {
  return requestClient.delete(`/recruitment/evaluation-scorecard/${id}`);
}

// =============================================================================
// CANDIDATE FORM API
// =============================================================================

export namespace CandidateFormApi {
  export interface CandidateForm {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface CandidateFormCreate {
    name: string;
    [key: string]: any;
  }

  export interface CandidateFormUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: CandidateForm[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getCandidateFormsApi(params?: CandidateFormApi.ListParams) {
  return requestClient.get<CandidateFormApi.ListResponse>('/recruitment/candidate-form/', { params });
}

export async function getCandidateFormApi(id: number) {
  return requestClient.get<CandidateFormApi.CandidateForm>(`/recruitment/candidate-form/${id}`);
}

export async function createCandidateFormApi(data: CandidateFormApi.CandidateFormCreate) {
  return requestClient.post<CandidateFormApi.CandidateForm>('/recruitment/candidate-form/', data);
}

export async function updateCandidateFormApi(id: number, data: CandidateFormApi.CandidateFormUpdate) {
  return requestClient.put<CandidateFormApi.CandidateForm>(`/recruitment/candidate-form/${id}`, data);
}

export async function deleteCandidateFormApi(id: number) {
  return requestClient.delete(`/recruitment/candidate-form/${id}`);
}

