/**
 * ComplianceService
 * Manages compliance rules, tracks policy adherence, and generates compliance reports
 */
export class ComplianceService {
  constructor(models) {
    this.models = models;
  }

  /**
   * Create a new compliance rule
   * @param {string} policy - Policy type (soc2, gdpr, hipaa, pci-dss, etc.)
   * @param {string} requirement - Description of the requirement
   * @param {boolean} enforcedByWorkflow - Whether this rule is enforced via workflow automation
   * @param {object} metadata - Optional metadata
   * @returns {object} Created compliance rule
   */
  async createRule(policy, requirement, enforcedByWorkflow = false, metadata = {}) {
    if (!policy) throw new Error('Policy is required');
    if (!requirement) throw new Error('Requirement is required');

    const rule = await this.models.ComplianceRule.create({
      policy,
      requirement,
      status: 'active',
      enforcedByWorkflow,
      metadata,
    });

    return rule;
  }

  /**
   * Get compliance rules
   * @param {string} policy - Optional: Filter by policy type
   * @param {string} status - Optional: Filter by status (active, inactive, archived)
   * @returns {array} Compliance rules
   */
  async getRules(policy = null, status = null) {
    const filters = {};

    if (policy) {
      filters.where = filters.where || [];
      filters.where.push(['policy', '=', policy]);
    }

    if (status) {
      filters.where = filters.where || [];
      filters.where.push(['status', '=', status]);
    }

    const result = await this.models.ComplianceRule.findAll(filters);
    return (result && result.rows) || [];
  }

  /**
   * Update a compliance rule
   * @param {number} ruleId - Rule ID
   * @param {object} updates - Fields to update
   * @returns {object} Updated rule
   */
  async updateRule(ruleId, updates) {
    if (!ruleId) throw new Error('Rule ID is required');

    const rule = await this.models.ComplianceRule.update(ruleId, updates);
    return rule;
  }

  /**
   * Generate a compliance report
   * @param {Date} startDate - Report start date
   * @param {Date} endDate - Report end date
   * @param {array} policies - Policies to include (e.g., ['soc2', 'gdpr'])
   * @param {number} generatedBy - User ID generating the report
   * @returns {object} Generated compliance report
   */
  async generateReport(startDate, endDate, policies = [], generatedBy) {
    if (!startDate || !endDate) throw new Error('Start date and end date are required');
    if (!generatedBy) throw new Error('Generated by user ID is required');

    // Build report name
    const startDateStr = startDate.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
    const endDateStr = endDate.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
    const reportName = `${startDateStr} - ${endDateStr} Compliance Report`;

    // Get rules for specified policies
    const ruleFilters = {};
    if (policies && policies.length > 0) {
      ruleFilters.where = policies.map((p) => ['policy', '=', p]);
    }

    const rulesResult = await this.models.ComplianceRule.findAll(ruleFilters);
    const rules = (rulesResult && rulesResult.rows) || [];

    // Calculate findings
    const findings = {};
    policies.forEach((policy) => {
      const policyRules = rules.filter((r) => r.policy === policy);
      findings[policy] = {
        compliant: policyRules.filter((r) => r.status === 'active').length,
        total: policyRules.length,
        percentage: policyRules.length > 0
          ? Math.round((policyRules.filter((r) => r.status === 'active').length / policyRules.length) * 100)
          : 0,
      };
    });

    // Calculate overall compliance
    const totalCompliant = Object.values(findings).reduce((sum, f) => sum + f.compliant, 0);
    const totalRules = Object.values(findings).reduce((sum, f) => sum + f.total, 0);
    const overallPercentage = totalRules > 0 ? Math.round((totalCompliant / totalRules) * 100) : 0;

    const summary = `Overall compliance: ${overallPercentage}%`;

    const report = await this.models.ComplianceReport.create({
      reportName,
      reportType: policies.join(','),
      startDate,
      endDate,
      findings,
      summary,
      generatedBy,
    });

    return report;
  }

  /**
   * Get compliance reports
   * @param {object} filters - Optional filters
   * @returns {array} Compliance reports
   */
  async getReports(filters = {}) {
    const result = await this.models.ComplianceReport.findAll(filters);
    return (result && result.rows) || [];
  }

  /**
   * Archive a compliance rule
   * @param {number} ruleId - Rule ID to archive
   * @returns {object} Archived rule
   */
  async archiveRule(ruleId) {
    return this.updateRule(ruleId, { status: 'archived' });
  }

  /**
   * Deactivate a compliance rule
   * @param {number} ruleId - Rule ID to deactivate
   * @returns {object} Deactivated rule
   */
  async deactivateRule(ruleId) {
    return this.updateRule(ruleId, { status: 'inactive' });
  }
}

export default ComplianceService;
