import { mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { slugify, parseFields, drizzleColumn, formInputType } from './field-map.js';
import { getTemplate } from './templates.js';

export function planModule({ name, label, fieldSpecs = [], template = null } = {}) {
  const technicalName = slugify(name);
  if (!technicalName) {
    throw new Error('Module name must contain letters or numbers');
  }
  let effectiveLabel = label;
  let effectiveSpecs = fieldSpecs;
  if (template) {
    const pack = getTemplate(template);
    if (!pack) {
      throw new Error(`Unknown template: ${template}`);
    }
    effectiveLabel = effectiveLabel || pack.label;
    if (!effectiveSpecs.length) {
      effectiveSpecs = pack.fields;
    }
  }
  const title = (effectiveLabel || name).trim().replace(/[_-]+/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
  const className = technicalName.replace(/(^|_)([a-z])/g, (_, __, c) => c.toUpperCase());
  const tableName = technicalName;
  const fields = parseFields(effectiveSpecs);
  return { technicalName, title, className, tableName, fields, template: template || null };
}

export function buildModuleFiles(plan) {
  const { technicalName, title, className, tableName, fields } = plan;
  const files = {};

  files['__manifest__.js'] = `export default {
  name: '${title}',
  technicalName: '${technicalName}',
  version: '1.0.0',
  summary: '${title} management',
  description: 'Auto-generated by create-lume-app.',
  author: 'Lume',
  license: 'MIT',
  category: 'Custom',
  application: true,
  installable: true,
  autoInstall: false,
  depends: ['base'],
  models: ['models/index.js'],
  api: ['api/index.js'],
  services: ['services/index.js'],
  frontend: {
    views: ['views/list.vue'],
  },
  menus: [
    { name: '${title}', path: '/${technicalName}', icon: 'lucide:box', sequence: 50 },
  ],
};
`;

  files['models/schema.js'] = `import { table, int, integer, varchar, text, boolean, timestamp } from '../../../core/db/dialect.js';
import { baseColumns } from '../../../core/db/drizzle-helpers.js';

const idCol = int || integer;

export const ${technicalName} = table('${tableName}', {
  ...baseColumns(),
${fields.map(drizzleColumn).join('\n')}
  createdBy: idCol('created_by'),
});
`;

  files['models/index.js'] = `export { ${technicalName} } from './schema.js';
`;

  files['services/service.js'] = `import { DrizzleAdapter } from '../../../core/db/adapters/drizzle-adapter.js';
import { ${technicalName} } from '../models/schema.js';

export class ${className}Service {
  constructor() {
    this.adapter = new DrizzleAdapter(${technicalName});
  }

  list(options = {}) {
    return this.adapter.findAll({
      limit: options.limit || 20,
      offset: options.offset || 0,
      order: [['createdAt', 'DESC']],
    });
  }

  create(data) {
    return this.adapter.create(data);
  }
}

export default ${className}Service;
`;

  files['services/index.js'] = `export { ${className}Service } from './service.js';
export { default } from './service.js';
`;

  files['api/routes.js'] = `import { Router } from 'express';
import { authenticate } from '../../../core/middleware/auth.js';
import { ${className}Service } from '../services/service.js';

const create${className}Routes = () => {
  const router = Router();
  const service = new ${className}Service();

  router.get('/', authenticate, async (req, res) => {
    try {
      const result = await service.list({ limit: Number(req.query.limit) || 20 });
      res.json({ success: true, data: result.rows || result });
    } catch (error) {
      res.status(500).json({ success: false, message: error.message });
    }
  });

  router.post('/', authenticate, async (req, res) => {
    try {
      const created = await service.create(req.body);
      res.status(201).json({ success: true, data: created });
    } catch (error) {
      res.status(400).json({ success: false, message: error.message });
    }
  });

  return router;
};

export default create${className}Routes;
`;

  files['api/index.js'] = `export { default } from './routes.js';
`;

  files['index.js'] = `import { ${className}Service } from './services/service.js';
import ${technicalName}Routes from './api/routes.js';
import { ${technicalName} } from './models/schema.js';
import { DrizzleAdapter } from '../../core/db/adapters/drizzle-adapter.js';

const ${technicalName}Adapter = new DrizzleAdapter(${technicalName});

export { ${className}Service, ${technicalName}Routes, ${technicalName}Adapter, ${technicalName} };

export default { ${className}Service, ${technicalName}Routes, ${technicalName}Adapter, ${technicalName} };
`;

  const formInputs = fields.map((f) => {
    const input = formInputType(f);
    if (input === 'textarea') {
      return `        <a-form-item label="${f.label}"><a-textarea v-model:value="form.${f.name}" :rows="3" /></a-form-item>`;
    }
    if (input === 'checkbox') {
      return `        <a-form-item label="${f.label}"><a-switch v-model:checked="form.${f.name}" /></a-form-item>`;
    }
    if (input === 'select') {
      const opts = (f.options || []).map((o) => `<a-select-option value="${o}">${o}</a-select-option>`).join('');
      return `        <a-form-item label="${f.label}"><a-select v-model:value="form.${f.name}" allow-clear>${opts}</a-select></a-form-item>`;
    }
    return `        <a-form-item label="${f.label}"><a-input v-model:value="form.${f.name}" type="${input}" /></a-form-item>`;
  }).join('\n');
  const formInit = fields.map((f) => `  ${f.name}: ${f.type === 'boolean' ? 'false' : "''"},`).join('\n');
  const columns = fields.slice(0, 4).map((f) => `    { title: '${f.label}', dataIndex: '${f.name}', key: '${f.name}' },`).join('\n');

  files['static/views/list.vue'] = `<script setup lang="ts">
import { ref, onMounted } from 'vue';

defineOptions({ name: '${className}ListView' });

const rows = ref<Record<string, unknown>[]>([]);
const loading = ref(false);
const form = ref<Record<string, unknown>>({
${formInit}
});

async function load() {
  loading.value = true;
  try {
    const res = await fetch('/api/${technicalName}');
    const body = await res.json();
    rows.value = Array.isArray(body.data) ? body.data : [];
  } finally {
    loading.value = false;
  }
}

async function create() {
  await fetch('/api/${technicalName}', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(form.value),
  });
  await load();
}

onMounted(load);
</script>

<template>
  <div class="p-6">
    <h1 class="text-2xl font-bold mb-4">${title}</h1>
    <a-card size="small" class="mb-4">
      <a-form layout="inline">
${formInputs}
        <a-form-item><a-button type="primary" @click="create">Add</a-button></a-form-item>
      </a-form>
    </a-card>
    <a-table :data-source="rows" :loading="loading" row-key="id" size="middle">
${columns}
    </a-table>
  </div>
</template>
`;

  files['static/api/index.js'] = `const BASE = '/api/${technicalName}';

async function request(path, options = {}) {
  const res = await fetch(BASE + path, {
    headers: { 'Content-Type': 'application/json', ...(options.headers || {}) },
    ...options,
  });
  if (!res.ok) {
    throw new Error('Request failed: ' + res.status);
  }
  return res.json();
}

export const list${className} = (params = {}) => {
  const qs = new URLSearchParams(params).toString();
  return request(qs ? '?' + qs : '');
};

export const create${className} = (data) => request('', { method: 'POST', body: JSON.stringify(data) });
`;

  files['README.md'] = `# ${title} module

Generated by create-lume-app. Drop this folder into \`backend/src/modules/\` — the
module loader discovers it automatically.

## Next steps

1. Review \`models/schema.js\` field types (select options, formula expressions).
2. Run table creation: \`node src/scripts/setupDrizzle.js\`.
3. Register the frontend route so the admin panel serves \`static/views/list.vue\`.
`;
  return files;
}

export function writeModule(targetDir, files) {
  for (const [rel, content] of Object.entries(files)) {
    const full = join(targetDir, rel);
    mkdirSync(join(targetDir, rel.split('/').slice(0, -1).join('/')), { recursive: true });
    writeFileSync(full, content);
  }
  return Object.keys(files);
}
