/**
 * PAYROLL Module API Client
 * Auto-generated by FastVue Module System
 */

import { requestClient } from '#/api/request';


// =============================================================================
// REPORTS API
// =============================================================================

export namespace ReportsApi {
  export interface Reports {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface ReportsCreate {
    name: string;
    [key: string]: any;
  }

  export interface ReportsUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Reports[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getReportssApi(params?: ReportsApi.ListParams) {
  return requestClient.get<ReportsApi.ListResponse>('/payroll/reports/', { params });
}

export async function getReportsApi(id: number) {
  return requestClient.get<ReportsApi.Reports>(`/payroll/reports/${id}`);
}

export async function createReportsApi(data: ReportsApi.ReportsCreate) {
  return requestClient.post<ReportsApi.Reports>('/payroll/reports/', data);
}

export async function updateReportsApi(id: number, data: ReportsApi.ReportsUpdate) {
  return requestClient.put<ReportsApi.Reports>(`/payroll/reports/${id}`, data);
}

export async function deleteReportsApi(id: number) {
  return requestClient.delete(`/payroll/reports/${id}`);
}

// =============================================================================
// SALARY API
// =============================================================================

export namespace SalaryApi {
  export interface Salary {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface SalaryCreate {
    name: string;
    [key: string]: any;
  }

  export interface SalaryUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Salary[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getSalarysApi(params?: SalaryApi.ListParams) {
  return requestClient.get<SalaryApi.ListResponse>('/payroll/salary/', { params });
}

export async function getSalaryApi(id: number) {
  return requestClient.get<SalaryApi.Salary>(`/payroll/salary/${id}`);
}

export async function createSalaryApi(data: SalaryApi.SalaryCreate) {
  return requestClient.post<SalaryApi.Salary>('/payroll/salary/', data);
}

export async function updateSalaryApi(id: number, data: SalaryApi.SalaryUpdate) {
  return requestClient.put<SalaryApi.Salary>(`/payroll/salary/${id}`, data);
}

export async function deleteSalaryApi(id: number) {
  return requestClient.delete(`/payroll/salary/${id}`);
}

// =============================================================================
// PAYSLIPS API
// =============================================================================

export namespace PayslipsApi {
  export interface Payslips {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface PayslipsCreate {
    name: string;
    [key: string]: any;
  }

  export interface PayslipsUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Payslips[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getPayslipssApi(params?: PayslipsApi.ListParams) {
  return requestClient.get<PayslipsApi.ListResponse>('/payroll/payslips/', { params });
}

export async function getPayslipsApi(id: number) {
  return requestClient.get<PayslipsApi.Payslips>(`/payroll/payslips/${id}`);
}

export async function createPayslipsApi(data: PayslipsApi.PayslipsCreate) {
  return requestClient.post<PayslipsApi.Payslips>('/payroll/payslips/', data);
}

export async function updatePayslipsApi(id: number, data: PayslipsApi.PayslipsUpdate) {
  return requestClient.put<PayslipsApi.Payslips>(`/payroll/payslips/${id}`, data);
}

export async function deletePayslipsApi(id: number) {
  return requestClient.delete(`/payroll/payslips/${id}`);
}

// =============================================================================
// BONUS API
// =============================================================================

export namespace BonusApi {
  export interface Bonus {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface BonusCreate {
    name: string;
    [key: string]: any;
  }

  export interface BonusUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Bonus[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getBonussApi(params?: BonusApi.ListParams) {
  return requestClient.get<BonusApi.ListResponse>('/payroll/bonus/', { params });
}

export async function getBonusApi(id: number) {
  return requestClient.get<BonusApi.Bonus>(`/payroll/bonus/${id}`);
}

export async function createBonusApi(data: BonusApi.BonusCreate) {
  return requestClient.post<BonusApi.Bonus>('/payroll/bonus/', data);
}

export async function updateBonusApi(id: number, data: BonusApi.BonusUpdate) {
  return requestClient.put<BonusApi.Bonus>(`/payroll/bonus/${id}`, data);
}

export async function deleteBonusApi(id: number) {
  return requestClient.delete(`/payroll/bonus/${id}`);
}

// =============================================================================
// ALLOWANCES API
// =============================================================================

export namespace AllowancesApi {
  export interface Allowances {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface AllowancesCreate {
    name: string;
    [key: string]: any;
  }

  export interface AllowancesUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Allowances[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getAllowancessApi(params?: AllowancesApi.ListParams) {
  return requestClient.get<AllowancesApi.ListResponse>('/payroll/allowances/', { params });
}

export async function getAllowancesApi(id: number) {
  return requestClient.get<AllowancesApi.Allowances>(`/payroll/allowances/${id}`);
}

export async function createAllowancesApi(data: AllowancesApi.AllowancesCreate) {
  return requestClient.post<AllowancesApi.Allowances>('/payroll/allowances/', data);
}

export async function updateAllowancesApi(id: number, data: AllowancesApi.AllowancesUpdate) {
  return requestClient.put<AllowancesApi.Allowances>(`/payroll/allowances/${id}`, data);
}

export async function deleteAllowancesApi(id: number) {
  return requestClient.delete(`/payroll/allowances/${id}`);
}

// =============================================================================
// DEDUCTIONS API
// =============================================================================

export namespace DeductionsApi {
  export interface Deductions {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface DeductionsCreate {
    name: string;
    [key: string]: any;
  }

  export interface DeductionsUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Deductions[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getDeductionssApi(params?: DeductionsApi.ListParams) {
  return requestClient.get<DeductionsApi.ListResponse>('/payroll/deductions/', { params });
}

export async function getDeductionsApi(id: number) {
  return requestClient.get<DeductionsApi.Deductions>(`/payroll/deductions/${id}`);
}

export async function createDeductionsApi(data: DeductionsApi.DeductionsCreate) {
  return requestClient.post<DeductionsApi.Deductions>('/payroll/deductions/', data);
}

export async function updateDeductionsApi(id: number, data: DeductionsApi.DeductionsUpdate) {
  return requestClient.put<DeductionsApi.Deductions>(`/payroll/deductions/${id}`, data);
}

export async function deleteDeductionsApi(id: number) {
  return requestClient.delete(`/payroll/deductions/${id}`);
}

// =============================================================================
// TAX API
// =============================================================================

export namespace TaxApi {
  export interface Tax {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface TaxCreate {
    name: string;
    [key: string]: any;
  }

  export interface TaxUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Tax[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getTaxsApi(params?: TaxApi.ListParams) {
  return requestClient.get<TaxApi.ListResponse>('/payroll/tax/', { params });
}

export async function getTaxApi(id: number) {
  return requestClient.get<TaxApi.Tax>(`/payroll/tax/${id}`);
}

export async function createTaxApi(data: TaxApi.TaxCreate) {
  return requestClient.post<TaxApi.Tax>('/payroll/tax/', data);
}

export async function updateTaxApi(id: number, data: TaxApi.TaxUpdate) {
  return requestClient.put<TaxApi.Tax>(`/payroll/tax/${id}`, data);
}

export async function deleteTaxApi(id: number) {
  return requestClient.delete(`/payroll/tax/${id}`);
}

// =============================================================================
// LOANS API
// =============================================================================

export namespace LoansApi {
  export interface Loans {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface LoansCreate {
    name: string;
    [key: string]: any;
  }

  export interface LoansUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Loans[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getLoanssApi(params?: LoansApi.ListParams) {
  return requestClient.get<LoansApi.ListResponse>('/payroll/loans/', { params });
}

export async function getLoansApi(id: number) {
  return requestClient.get<LoansApi.Loans>(`/payroll/loans/${id}`);
}

export async function createLoansApi(data: LoansApi.LoansCreate) {
  return requestClient.post<LoansApi.Loans>('/payroll/loans/', data);
}

export async function updateLoansApi(id: number, data: LoansApi.LoansUpdate) {
  return requestClient.put<LoansApi.Loans>(`/payroll/loans/${id}`, data);
}

export async function deleteLoansApi(id: number) {
  return requestClient.delete(`/payroll/loans/${id}`);
}

// =============================================================================
// REIMBURSEMENTS API
// =============================================================================

export namespace ReimbursementsApi {
  export interface Reimbursements {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface ReimbursementsCreate {
    name: string;
    [key: string]: any;
  }

  export interface ReimbursementsUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Reimbursements[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getReimbursementssApi(params?: ReimbursementsApi.ListParams) {
  return requestClient.get<ReimbursementsApi.ListResponse>('/payroll/reimbursements/', { params });
}

export async function getReimbursementsApi(id: number) {
  return requestClient.get<ReimbursementsApi.Reimbursements>(`/payroll/reimbursements/${id}`);
}

export async function createReimbursementsApi(data: ReimbursementsApi.ReimbursementsCreate) {
  return requestClient.post<ReimbursementsApi.Reimbursements>('/payroll/reimbursements/', data);
}

export async function updateReimbursementsApi(id: number, data: ReimbursementsApi.ReimbursementsUpdate) {
  return requestClient.put<ReimbursementsApi.Reimbursements>(`/payroll/reimbursements/${id}`, data);
}

export async function deleteReimbursementsApi(id: number) {
  return requestClient.delete(`/payroll/reimbursements/${id}`);
}

