/**
 * EMPLOYEE Module API Client
 * Auto-generated by FastVue Module System
 */

import { requestClient } from '#/api/request';


// =============================================================================
// REPORTS API
// =============================================================================

export namespace ReportsApi {
  export interface Reports {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface ReportsCreate {
    name: string;
    [key: string]: any;
  }

  export interface ReportsUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Reports[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getReportssApi(params?: ReportsApi.ListParams) {
  return requestClient.get<ReportsApi.ListResponse>('/employee/reports/', { params });
}

export async function getReportsApi(id: number) {
  return requestClient.get<ReportsApi.Reports>(`/employee/reports/${id}`);
}

export async function createReportsApi(data: ReportsApi.ReportsCreate) {
  return requestClient.post<ReportsApi.Reports>('/employee/reports/', data);
}

export async function updateReportsApi(id: number, data: ReportsApi.ReportsUpdate) {
  return requestClient.put<ReportsApi.Reports>(`/employee/reports/${id}`, data);
}

export async function deleteReportsApi(id: number) {
  return requestClient.delete(`/employee/reports/${id}`);
}

// =============================================================================
// LIST API
// =============================================================================

export namespace ListApi {
  export interface List {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface ListCreate {
    name: string;
    [key: string]: any;
  }

  export interface ListUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: List[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getListsApi(params?: ListApi.ListParams) {
  return requestClient.get<ListApi.ListResponse>('/employee/list/', { params });
}

export async function getListApi(id: number) {
  return requestClient.get<ListApi.List>(`/employee/list/${id}`);
}

export async function createListApi(data: ListApi.ListCreate) {
  return requestClient.post<ListApi.List>('/employee/list/', data);
}

export async function updateListApi(id: number, data: ListApi.ListUpdate) {
  return requestClient.put<ListApi.List>(`/employee/list/${id}`, data);
}

export async function deleteListApi(id: number) {
  return requestClient.delete(`/employee/list/${id}`);
}

// =============================================================================
// DOCUMENTS API
// =============================================================================

export namespace DocumentsApi {
  export interface Documents {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface DocumentsCreate {
    name: string;
    [key: string]: any;
  }

  export interface DocumentsUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Documents[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getDocumentssApi(params?: DocumentsApi.ListParams) {
  return requestClient.get<DocumentsApi.ListResponse>('/employee/documents/', { params });
}

export async function getDocumentsApi(id: number) {
  return requestClient.get<DocumentsApi.Documents>(`/employee/documents/${id}`);
}

export async function createDocumentsApi(data: DocumentsApi.DocumentsCreate) {
  return requestClient.post<DocumentsApi.Documents>('/employee/documents/', data);
}

export async function updateDocumentsApi(id: number, data: DocumentsApi.DocumentsUpdate) {
  return requestClient.put<DocumentsApi.Documents>(`/employee/documents/${id}`, data);
}

export async function deleteDocumentsApi(id: number) {
  return requestClient.delete(`/employee/documents/${id}`);
}

// =============================================================================
// NOTES API
// =============================================================================

export namespace NotesApi {
  export interface Notes {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface NotesCreate {
    name: string;
    [key: string]: any;
  }

  export interface NotesUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Notes[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getNotessApi(params?: NotesApi.ListParams) {
  return requestClient.get<NotesApi.ListResponse>('/employee/notes/', { params });
}

export async function getNotesApi(id: number) {
  return requestClient.get<NotesApi.Notes>(`/employee/notes/${id}`);
}

export async function createNotesApi(data: NotesApi.NotesCreate) {
  return requestClient.post<NotesApi.Notes>('/employee/notes/', data);
}

export async function updateNotesApi(id: number, data: NotesApi.NotesUpdate) {
  return requestClient.put<NotesApi.Notes>(`/employee/notes/${id}`, data);
}

export async function deleteNotesApi(id: number) {
  return requestClient.delete(`/employee/notes/${id}`);
}

// =============================================================================
// BONUS POINTS API
// =============================================================================

export namespace BonusPointsApi {
  export interface BonusPoints {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface BonusPointsCreate {
    name: string;
    [key: string]: any;
  }

  export interface BonusPointsUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: BonusPoints[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getBonusPointssApi(params?: BonusPointsApi.ListParams) {
  return requestClient.get<BonusPointsApi.ListResponse>('/employee/bonus-points/', { params });
}

export async function getBonusPointsApi(id: number) {
  return requestClient.get<BonusPointsApi.BonusPoints>(`/employee/bonus-points/${id}`);
}

export async function createBonusPointsApi(data: BonusPointsApi.BonusPointsCreate) {
  return requestClient.post<BonusPointsApi.BonusPoints>('/employee/bonus-points/', data);
}

export async function updateBonusPointsApi(id: number, data: BonusPointsApi.BonusPointsUpdate) {
  return requestClient.put<BonusPointsApi.BonusPoints>(`/employee/bonus-points/${id}`, data);
}

export async function deleteBonusPointsApi(id: number) {
  return requestClient.delete(`/employee/bonus-points/${id}`);
}

// =============================================================================
// DISCIPLINARY ACTIONS API
// =============================================================================

export namespace DisciplinaryActionsApi {
  export interface DisciplinaryActions {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface DisciplinaryActionsCreate {
    name: string;
    [key: string]: any;
  }

  export interface DisciplinaryActionsUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: DisciplinaryActions[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getDisciplinaryActionssApi(params?: DisciplinaryActionsApi.ListParams) {
  return requestClient.get<DisciplinaryActionsApi.ListResponse>('/employee/disciplinary-actions/', { params });
}

export async function getDisciplinaryActionsApi(id: number) {
  return requestClient.get<DisciplinaryActionsApi.DisciplinaryActions>(`/employee/disciplinary-actions/${id}`);
}

export async function createDisciplinaryActionsApi(data: DisciplinaryActionsApi.DisciplinaryActionsCreate) {
  return requestClient.post<DisciplinaryActionsApi.DisciplinaryActions>('/employee/disciplinary-actions/', data);
}

export async function updateDisciplinaryActionsApi(id: number, data: DisciplinaryActionsApi.DisciplinaryActionsUpdate) {
  return requestClient.put<DisciplinaryActionsApi.DisciplinaryActions>(`/employee/disciplinary-actions/${id}`, data);
}

export async function deleteDisciplinaryActionsApi(id: number) {
  return requestClient.delete(`/employee/disciplinary-actions/${id}`);
}

// =============================================================================
// POLICIES API
// =============================================================================

export namespace PoliciesApi {
  export interface Policies {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface PoliciesCreate {
    name: string;
    [key: string]: any;
  }

  export interface PoliciesUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Policies[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getPoliciessApi(params?: PoliciesApi.ListParams) {
  return requestClient.get<PoliciesApi.ListResponse>('/employee/policies/', { params });
}

export async function getPoliciesApi(id: number) {
  return requestClient.get<PoliciesApi.Policies>(`/employee/policies/${id}`);
}

export async function createPoliciesApi(data: PoliciesApi.PoliciesCreate) {
  return requestClient.post<PoliciesApi.Policies>('/employee/policies/', data);
}

export async function updatePoliciesApi(id: number, data: PoliciesApi.PoliciesUpdate) {
  return requestClient.put<PoliciesApi.Policies>(`/employee/policies/${id}`, data);
}

export async function deletePoliciesApi(id: number) {
  return requestClient.delete(`/employee/policies/${id}`);
}

// =============================================================================
// SETTINGS API
// =============================================================================

export namespace SettingsApi {
  export interface Settings {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface SettingsCreate {
    name: string;
    [key: string]: any;
  }

  export interface SettingsUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Settings[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getSettingssApi(params?: SettingsApi.ListParams) {
  return requestClient.get<SettingsApi.ListResponse>('/employee/settings/', { params });
}

export async function getSettingsApi(id: number) {
  return requestClient.get<SettingsApi.Settings>(`/employee/settings/${id}`);
}

export async function createSettingsApi(data: SettingsApi.SettingsCreate) {
  return requestClient.post<SettingsApi.Settings>('/employee/settings/', data);
}

export async function updateSettingsApi(id: number, data: SettingsApi.SettingsUpdate) {
  return requestClient.put<SettingsApi.Settings>(`/employee/settings/${id}`, data);
}

export async function deleteSettingsApi(id: number) {
  return requestClient.delete(`/employee/settings/${id}`);
}

// =============================================================================
// FORM API
// =============================================================================

export namespace FormApi {
  export interface Form {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface FormCreate {
    name: string;
    [key: string]: any;
  }

  export interface FormUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Form[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getFormsApi(params?: FormApi.ListParams) {
  return requestClient.get<FormApi.ListResponse>('/employee/form/', { params });
}

export async function getFormApi(id: number) {
  return requestClient.get<FormApi.Form>(`/employee/form/${id}`);
}

export async function createFormApi(data: FormApi.FormCreate) {
  return requestClient.post<FormApi.Form>('/employee/form/', data);
}

export async function updateFormApi(id: number, data: FormApi.FormUpdate) {
  return requestClient.put<FormApi.Form>(`/employee/form/${id}`, data);
}

export async function deleteFormApi(id: number) {
  return requestClient.delete(`/employee/form/${id}`);
}

// =============================================================================
// DETAIL API
// =============================================================================

export namespace DetailApi {
  export interface Detail {
    id: number;
    name: string;
    created_at: string;
    updated_at: string | null;
    [key: string]: any;
  }

  export interface DetailCreate {
    name: string;
    [key: string]: any;
  }

  export interface DetailUpdate {
    name?: string;
    [key: string]: any;
  }

  export interface ListParams {
    skip?: number;
    limit?: number;
    search?: string;
  }

  export interface ListResponse {
    items: Detail[];
    total: number;
    page: number;
    page_size: number;
  }
}

export async function getDetailsApi(params?: DetailApi.ListParams) {
  return requestClient.get<DetailApi.ListResponse>('/employee/detail/', { params });
}

export async function getDetailApi(id: number) {
  return requestClient.get<DetailApi.Detail>(`/employee/detail/${id}`);
}

export async function createDetailApi(data: DetailApi.DetailCreate) {
  return requestClient.post<DetailApi.Detail>('/employee/detail/', data);
}

export async function updateDetailApi(id: number, data: DetailApi.DetailUpdate) {
  return requestClient.put<DetailApi.Detail>(`/employee/detail/${id}`, data);
}

export async function deleteDetailApi(id: number) {
  return requestClient.delete(`/employee/detail/${id}`);
}

