export enum EntityFieldType {
  STRING = 'string',
  TEXT = 'text',
  INTEGER = 'integer',
  FLOAT = 'float',
  BOOLEAN = 'boolean',
  DATE = 'date',
  DATETIME = 'datetime',
  SELECT = 'select',
  MULTISELECT = 'multiselect',
  JSON = 'json',
  EMAIL = 'email',
  URL = 'url',
  PHONE = 'phone',
  LOOKUP = 'lookup',
  FORMULA = 'formula',
  ROLLUP = 'rollup',
}
